spring.application.name=Job-tracker-APi
# 1. Database Connection (Postgres default port is 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracker_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# 2. SQL Dialect (Tells Hibernate how to speak Postgres)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. The "Auto" Table Creator
# 'update' will create the 'job_application' table automatically based on your @Entity class
spring.jpa.hibernate.ddl-auto=update

# 4. Debugging: This prints the SQL queries in your console so you can learn
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Force the version to a format the UI can render
springdoc.api-docs.version=OPENAPI_3_0
# Optional: Ensure the path is exactly what the UI expects
springdoc.swagger-ui.path=/swagger-ui.html
